# Generated by Django 5.0.6 on 2024-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrentcontract",
            name="name",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
